# -*- coding: utf-8 -*-
"""Portfolio_Optimization_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HNMdQtsTIYrfFJNkkY-Bbn0D0muD7kq
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.optimize import minimize

plt.style.use("seaborn-v0_8-whitegrid")
sns.set_palette("Set2")

TRADING_DAYS = 252
RISK_FREE_RATE = 0.04

# Diversified ETF universe
TICKERS = [
    "SPY",  # US large-cap equities
    "QQQ",  # US growth/technology
    "IWM",  # US small-cap equities
    "EFA",  # Developed international equities
    "EEM",  # Emerging-market equities
    "TLT",  # Long-term US Treasury bonds
    "GLD",  # Gold
    "VNQ",  # US real estate
]

START_DATE = "2015-01-01"
END_DATE = None

raw_data = yf.download(
    TICKERS,
    start=START_DATE,
    end=END_DATE,
    auto_adjust=True,
    progress=False
)

prices = raw_data["Close"].dropna()

print("Observations:", len(prices))
print("Beginning:", prices.index.min().date())
print("Ending:", prices.index.max().date())

display(prices.tail())

normalized_prices = prices / prices.iloc[0] * 100

ax = normalized_prices.plot(figsize=(14, 7), linewidth=1.7)

ax.set_title("Growth of $100 by Asset", fontsize=16)
ax.set_ylabel("Portfolio Value")
ax.set_xlabel("")
ax.legend(ncol=4)

plt.show()

normalized_prices = prices / prices.iloc[0] * 100

ax = normalized_prices.plot(figsize=(14, 7), linewidth=1.7)

ax.set_title("Growth of $100 by Asset", fontsize=16)
ax.set_ylabel("Portfolio Value")
ax.set_xlabel("")
ax.legend(ncol=4)

plt.show()

returns = prices.pct_change().dropna()

annual_returns = returns.mean() * TRADING_DAYS
annual_volatility = returns.std() * np.sqrt(TRADING_DAYS)
sharpe_ratios = (
    annual_returns - RISK_FREE_RATE
) / annual_volatility

statistics = pd.DataFrame({
    "Annual Return": annual_returns,
    "Annual Volatility": annual_volatility,
    "Sharpe Ratio": sharpe_ratios
}).sort_values("Sharpe Ratio", ascending=False)

display(
    statistics.style.format({
        "Annual Return": "{:.2%}",
        "Annual Volatility": "{:.2%}",
        "Sharpe Ratio": "{:.2f}"
    })
)

plt.figure(figsize=(10, 7))

sns.heatmap(
    returns.corr(),
    annot=True,
    fmt=".2f",
    cmap="RdYlGn",
    center=0,
    square=True
)

plt.title("Daily Return Correlations", fontsize=15)
plt.show()

expected_returns = returns.mean() * TRADING_DAYS
covariance_matrix = returns.cov() * TRADING_DAYS

number_of_assets = len(TICKERS)


def portfolio_return(weights):
    return float(np.dot(weights, expected_returns))


def portfolio_volatility(weights):
    variance = np.dot(
        weights.T,
        np.dot(covariance_matrix, weights)
    )
    return float(np.sqrt(variance))


def portfolio_sharpe(weights):
    volatility = portfolio_volatility(weights)

    if volatility == 0:
        return np.nan

    return (
        portfolio_return(weights) - RISK_FREE_RATE
    ) / volatility


def negative_sharpe(weights):
    return -portfolio_sharpe(weights)


initial_weights = np.repeat(
    1 / number_of_assets,
    number_of_assets
)

bounds = tuple(
    (0, 1) for _ in range(number_of_assets)
)

fully_invested_constraint = {
    "type": "eq",
    "fun": lambda weights: np.sum(weights) - 1
}

max_sharpe_result = minimize(
    negative_sharpe,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=fully_invested_constraint
)

if not max_sharpe_result.success:
    raise RuntimeError(max_sharpe_result.message)

max_sharpe_weights = max_sharpe_result.x

max_sharpe_portfolio = {
    "Return": portfolio_return(max_sharpe_weights),
    "Volatility": portfolio_volatility(max_sharpe_weights),
    "Sharpe": portfolio_sharpe(max_sharpe_weights)
}

print("Maximum-Sharpe portfolio")
print(max_sharpe_portfolio)

min_volatility_result = minimize(
    portfolio_volatility,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=fully_invested_constraint
)

if not min_volatility_result.success:
    raise RuntimeError(min_volatility_result.message)

min_volatility_weights = min_volatility_result.x

min_volatility_portfolio = {
    "Return": portfolio_return(min_volatility_weights),
    "Volatility": portfolio_volatility(min_volatility_weights),
    "Sharpe": portfolio_sharpe(min_volatility_weights)
}

print("Minimum-volatility portfolio")
print(min_volatility_portfolio)

equal_weights = np.repeat(
    1 / number_of_assets,
    number_of_assets
)

allocations = pd.DataFrame({
    "Equal Weight": equal_weights,
    "Maximum Sharpe": max_sharpe_weights,
    "Minimum Volatility": min_volatility_weights
}, index=TICKERS)

display(allocations.style.format("{:.2%}"))

allocations.plot(
    kind="bar",
    figsize=(14, 7)
)

plt.title("Portfolio Allocations", fontsize=16)
plt.ylabel("Weight")
plt.xlabel("Asset")
plt.xticks(rotation=0)
plt.legend()
plt.show()

rng = np.random.default_rng(42)
number_of_portfolios = 20_000

simulation_results = []

for _ in range(number_of_portfolios):
    weights = rng.random(number_of_assets)
    weights /= weights.sum()

    port_return = portfolio_return(weights)
    port_volatility = portfolio_volatility(weights)
    port_sharpe = (
        port_return - RISK_FREE_RATE
    ) / port_volatility

    simulation_results.append(
        [port_return, port_volatility, port_sharpe]
    )

simulation_results = pd.DataFrame(
    simulation_results,
    columns=["Return", "Volatility", "Sharpe"]
)

plt.figure(figsize=(12, 7))

scatter = plt.scatter(
    simulation_results["Volatility"],
    simulation_results["Return"],
    c=simulation_results["Sharpe"],
    cmap="viridis",
    alpha=0.35,
    s=12
)

plt.scatter(
    max_sharpe_portfolio["Volatility"],
    max_sharpe_portfolio["Return"],
    marker="*",
    s=350,
    color="red",
    label="Maximum Sharpe"
)

plt.scatter(
    min_volatility_portfolio["Volatility"],
    min_volatility_portfolio["Return"],
    marker="X",
    s=220,
    color="blue",
    label="Minimum Volatility"
)

plt.colorbar(scatter, label="Sharpe Ratio")
plt.title("Simulated Portfolio Opportunity Set", fontsize=16)
plt.xlabel("Annualized Volatility")
plt.ylabel("Annualized Expected Return")
plt.legend()
plt.show()

portfolio_returns = pd.DataFrame(index=returns.index)

portfolio_returns["Equal Weight"] = (
    returns @ equal_weights
)

portfolio_returns["Maximum Sharpe"] = (
    returns @ max_sharpe_weights
)

portfolio_returns["Minimum Volatility"] = (
    returns @ min_volatility_weights
)

portfolio_growth = (
    1 + portfolio_returns
).cumprod()

portfolio_growth.plot(
    figsize=(14, 7),
    linewidth=2
)

plt.title("Portfolio Growth: $1 Initial Investment", fontsize=16)
plt.ylabel("Portfolio Value")
plt.xlabel("")
plt.show()

def maximum_drawdown(return_series):
    wealth = (1 + return_series).cumprod()
    previous_peak = wealth.cummax()
    drawdown = wealth / previous_peak - 1

    return drawdown.min()


def annualized_return(return_series):
    years = len(return_series) / TRADING_DAYS

    return (
        (1 + return_series).prod() ** (1 / years)
        - 1
    )


def annualized_volatility(return_series):
    return (
        return_series.std()
        * np.sqrt(TRADING_DAYS)
    )


def calculate_metrics(return_series):
    ann_return = annualized_return(return_series)
    ann_volatility = annualized_volatility(return_series)

    sharpe = (
        ann_return - RISK_FREE_RATE
    ) / ann_volatility

    downside_returns = return_series[
        return_series < 0
    ]

    downside_deviation = (
        downside_returns.std()
        * np.sqrt(TRADING_DAYS)
    )

    sortino = (
        (ann_return - RISK_FREE_RATE)
        / downside_deviation
        if downside_deviation > 0
        else np.nan
    )

    return pd.Series({
        "Annual Return": ann_return,
        "Annual Volatility": ann_volatility,
        "Sharpe Ratio": sharpe,
        "Sortino Ratio": sortino,
        "Maximum Drawdown": maximum_drawdown(
            return_series
        )
    })


performance_table = portfolio_returns.apply(
    calculate_metrics
).T

display(
    performance_table.style.format({
        "Annual Return": "{:.2%}",
        "Annual Volatility": "{:.2%}",
        "Sharpe Ratio": "{:.2f}",
        "Sortino Ratio": "{:.2f}",
        "Maximum Drawdown": "{:.2%}"
    })
)

wealth = (1 + portfolio_returns).cumprod()
running_peaks = wealth.cummax()
drawdowns = wealth / running_peaks - 1

drawdowns.plot(
    figsize=(14, 7),
    linewidth=1.8
)

plt.title("Portfolio Drawdowns", fontsize=16)
plt.ylabel("Drawdown")
plt.xlabel("")
plt.axhline(0, color="black", linewidth=1)
plt.show()

def historical_var(return_series, confidence=0.95):
    cutoff = np.quantile(
        return_series,
        1 - confidence
    )

    return -cutoff


def expected_shortfall(return_series, confidence=0.95):
    cutoff = np.quantile(
        return_series,
        1 - confidence
    )

    tail_returns = return_series[
        return_series <= cutoff
    ]

    return -tail_returns.mean()


risk_table = pd.DataFrame(index=portfolio_returns.columns)

risk_table["Daily VaR 95%"] = portfolio_returns.apply(
    historical_var
)

risk_table["Daily Expected Shortfall 95%"] = (
    portfolio_returns.apply(expected_shortfall)
)

display(risk_table.style.format("{:.2%}"))

rolling_volatility = (
    portfolio_returns
    .rolling(63)
    .std()
    * np.sqrt(TRADING_DAYS)
)

rolling_volatility.plot(
    figsize=(14, 7),
    linewidth=1.7
)

plt.title("63-Day Rolling Annualized Volatility", fontsize=16)
plt.ylabel("Annualized Volatility")
plt.xlabel("")
plt.show()

best_sharpe_name = (
    performance_table["Sharpe Ratio"].idxmax()
)

lowest_volatility_name = (
    performance_table["Annual Volatility"].idxmin()
)

smallest_drawdown_name = (
    performance_table["Maximum Drawdown"].idxmax()
)

print("PORTFOLIO RESEARCH SUMMARY")
print("-" * 50)
print(f"Best realized Sharpe ratio: {best_sharpe_name}")
print(f"Lowest realized volatility: {lowest_volatility_name}")
print(f"Smallest maximum drawdown: {smallest_drawdown_name}")

print("\nMaximum-Sharpe allocation:")
for ticker, weight in zip(
    TICKERS,
    max_sharpe_weights
):
    if weight >= 0.001:
        print(f"{ticker}: {weight:.2%}")

